name: Lint

on:
  workflow_call:

env:
  REPO: ${{ github.event.repository.name }}
  MOD_PATH: ~/.vmodules/bartender

jobs:
  fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Restore Cache
        uses: actions/cache/restore@v3
        with:
          path: vlang
          key: ${{ runner.os }}-v-
          fail-on-cache-miss: true

      - name: Setup V
        uses: vlang/setup-v@v1.3

      - name: Checkout ${{ env.REPO }}
        uses: actions/checkout@v3
        with:
          path: ${{ env.REPO }}

      - name: Copy ${{ env.REPO }} to ${{ env.MOD_PATH }}
        run: cp -r ${{ env.REPO }} ${{ env.MOD_PATH }}

      - name: Check Formatting
        run: v fmt -verify ${{ env.MOD_PATH }}

  # Vet includes checking public functions without documentation
  # Disable until public functions are documented
  # vet:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Restore V Cache
  #       uses: actions/cache/restore@v3
  #       with:
  #         path: ${{ env.WORK_PATH }}vlang/
  #         key: ${{ runner.os }}-v-
  #         fail-on-cache-miss: true
  #
  #     - name: Setup V
  #       uses: vlang/setup-v@v1.3
  #
  #     - name: Setup libcurl
  #       run: sudo apt install libcurl4-openssl-dev
  #
  #     - name: Checkout ${{ github.event.repository.name }}
  #       uses: actions/checkout@v3
  #
  #     - name: Copy ${{ env.REPO }} to ${{ env.MOD_PATH }}
  #       run: cp -r ${{ env.REPO }} ${{ env.MOD_PATH }}
  #
  #     - name: Vet ${{ github.event.repository.name }}
  #       run: v vet -W ${{ env.MOD_PATH }}/src/
